import { BELEGE24_DOCUMENT_FORMAT, BELEGE24_GENERATOR_VERSION, BELEGE24_SCHEMA_VERSION } from './constants.js';
import { readBelege24DocumentFromPdf } from './pdfAttachment.js';
import type {
  Belege24Document, BusinessLetterDocument, BusinessLetterGeneratorState, DeliveryNoteDocument, DocumentAddress, DocumentFooter, FieldConfiguration,
  InvoiceTextBlock, OfferDocument, ReceiptDocument, ReceiptGeneratorState, ReceiptPersistedGeneratorState, SelfReceiptDocument, SelfReceiptGeneratorState, SharedData,
} from './types.js';

type BusinessData = {
  sender: { companyName: string; returnAddress: string; address: DocumentAddress; contact: { email: string; phone: string; fax: string; website: string } };
  recipient: { companyName: string; attention: string; name: string; address: DocumentAddress };
  details: Record<string, string>;
  references: Record<string, string>;
  footer: DocumentFooter;
};
export type OfferEditorState = { labels: Record<string, string>; offerData: BusinessData; positions: Array<{ id: string; description: string; unitPrice: string; quantity: string; unit: string; taxRate: string }>; textBlocks: InvoiceTextBlock[]; fieldConfig: BusinessFieldConfig };
export type DeliveryNoteEditorState = { labels: Record<string, string>; deliveryNoteData: BusinessData; positions: Array<{ id: string; quantity: string; unit: string; description: string; deliveryDate: string; note: string }>; textBlocks: InvoiceTextBlock[]; fieldConfig: BusinessFieldConfig };
export type SelfReceiptEditorState = SelfReceiptGeneratorState;
type BusinessFieldConfig = { contact: FieldConfiguration; details: FieldConfiguration; recipient: FieldConfiguration; footerMiddle: FieldConfiguration };
type RestoreResult<T> = { status: 'valid'; state: T } | { status: 'invalid' } | { status: 'wrong-document-type' };
export type AdditionalPdfImportResult<T> = { status: 'valid'; state: T; message: string } | { status: 'not-found' | 'invalid-data' | 'unsupported' | 'wrong-document-type' | 'unreadable-pdf'; message: string };

const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const offerLabels = ['title', 'offerNumber', 'offerDate', 'validUntil', 'internalNumber', 'externalNumber', 'customerNumber', 'position', 'description', 'unitPrice', 'quantity', 'unit', 'tax', 'total', 'net', 'taxAmount', 'grandTotal', 'contactEmail', 'contactPhone', 'contactFax', 'contactWebsite'];
const deliveryLabels = ['title', 'deliveryNoteNumber', 'deliveryDate', 'orderDate', 'internalReference', 'externalReference', 'customerReference', 'position', 'quantity', 'unit', 'description', 'contactEmail', 'contactPhone', 'contactFax', 'contactWebsite'];
const receiptLabels = ['title', 'receiptId', 'receiptDate', 'paymentDate', 'internalReference', 'externalReference', 'netAmount', 'taxRate', 'taxAmount', 'grossAmount', 'amountInWords', 'from', 'purpose', 'placeDate', 'bookingNote', 'receiverSignature'];
const selfReceiptLabels = ['title', 'recipientTitle', 'selfReceiptId', 'receiptDate', 'expenseDate', 'internalReference', 'externalReference', 'costCenter', 'position', 'description', 'netAmount', 'tax', 'grossAmount', 'net', 'taxAmount', 'grandTotal', 'occasion', 'reason', 'settlementType', 'location', 'contactEmail', 'contactPhone', 'contactFax', 'contactWebsite'];
const selfReceiptExpenseInfoFields = ['reason', 'settlementType', 'location'];
const legacySelfReceiptExpenseInfoFields = ['occasion', ...selfReceiptExpenseInfoFields];
const selfReceiptSignatureFields = ['signature'];
const shortSelfReceiptSignatureFields = ['signature'];
const shortSelfReceiptHeaderFields = ['company', 'streetLine', 'cityLine'];
const businessLetterLabels = ['title', 'yourReference', 'ourReference', 'contactPerson', 'place', 'letterDate', 'subject', 'salutation', 'body', 'closing', 'signerName', 'signerRole', 'attachments', 'contactEmail', 'contactPhone', 'contactFax', 'contactWebsite'];
const businessConfigFields = { contact: ['email', 'phone', 'fax', 'website'], details: ['offerNumber', 'offerDate', 'validUntil', 'internalNumber', 'externalNumber', 'customerNumber'], recipient: ['attention', 'name'], footerMiddle: ['vatId', 'taxNumber', 'commercialRegister', 'managingDirector'] };

function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
function hasStrings(value: unknown, keys: readonly string[]): boolean { return isRecord(value) && keys.every((key) => typeof value[key] === 'string'); }
function isStringRecord(value: unknown, required: readonly string[] = []): boolean { return isRecord(value) && required.every((key) => typeof value[key] === 'string') && Object.values(value).every((entry) => typeof entry === 'string'); }
function isAddress(value: unknown): boolean { return hasStrings(value, ['street', 'houseNumber', 'postalCode', 'city']); }
function isTextBlocks(value: unknown, ids: readonly string[]): boolean { return Array.isArray(value) && value.length === ids.length && value.every((block, index) => isRecord(block) && block.id === ids[index] && hasStrings(block, ['id', 'label', 'value']) && typeof block.visible === 'boolean'); }
function isConfig(value: unknown, fields: readonly string[]): boolean { return isRecord(value) && Array.isArray(value.hidden) && Array.isArray(value.order) && value.hidden.every((field) => typeof field === 'string' && fields.includes(field)) && value.order.length === fields.length && new Set(value.order).size === fields.length && value.order.every((field) => typeof field === 'string' && fields.includes(field)); }
function isSelfReceiptExpenseInfoConfig(value: unknown): value is FieldConfiguration { return isConfig(value, selfReceiptExpenseInfoFields) || isConfig(value, legacySelfReceiptExpenseInfoFields); }
function isBusinessFieldConfig(value: unknown, detailFields: readonly string[]): boolean { return isRecord(value) && isConfig(value.contact, businessConfigFields.contact) && isConfig(value.details, detailFields) && isConfig(value.recipient, businessConfigFields.recipient) && isConfig(value.footerMiddle, businessConfigFields.footerMiddle); }
function isFooter(value: unknown): boolean { return isRecord(value) && hasStrings(value.company, ['companyName', 'street', 'houseNumber', 'postalCode', 'city', 'extra']) && hasStrings(value.tax, ['vatIdLabel', 'vatId', 'taxNumberLabel', 'taxNumber', 'commercialRegister', 'representation']) && hasStrings(value.bank, ['bankName', 'ibanLabel', 'iban', 'bicLabel', 'bic', 'bankExtra']); }
function isBusinessData(value: unknown, detailFields: readonly string[], referenceFields: readonly string[]): boolean { return isRecord(value) && isRecord(value.sender) && hasStrings(value.sender, ['companyName', 'returnAddress']) && isAddress(value.sender.address) && hasStrings(isRecord(value.sender) ? value.sender.contact : undefined, ['email', 'phone', 'fax', 'website']) && isRecord(value.recipient) && hasStrings(value.recipient, ['companyName', 'attention', 'name']) && isAddress(value.recipient.address) && isStringRecord(value.details, detailFields) && isStringRecord(value.references, referenceFields) && isFooter(value.footer); }
function isMetadata(value: unknown, documentType: string): boolean { return isRecord(value) && value.documentType === documentType && typeof value.documentId === 'string' && uuidPattern.test(value.documentId) && typeof value.createdAt === 'string' && !Number.isNaN(Date.parse(value.createdAt)) && new Date(value.createdAt).toISOString() === value.createdAt && typeof value.generatorVersion === 'string' && value.generatorVersion.length > 0; }
function isSharedData(value: unknown): boolean { return isRecord(value) && isRecord(value.sender) && hasStrings(value.sender, ['brandName', 'senderLine']) && isAddress(value.sender.address) && isRecord(value.sender.companyFooter) && isAddress(value.sender.companyFooter.companyAddress) && Array.isArray(value.sender.companyFooter.columns) && value.sender.companyFooter.columns.length === 3 && value.sender.companyFooter.columns.every((column) => isRecord(column) && Array.isArray(column.fields) && column.fields.length === 4 && column.fields.every((field) => hasStrings(field, ['key', 'value']))) && isRecord(value.recipient) && hasStrings(value.recipient, ['company', 'contactPerson', 'department', 'streetAndNumber', 'countryPostalCodeAndCity', 'customerNumber']) && isAddress(value.recipient.address); }
function hasBaseDocument(value: unknown, documentType: string): value is Record<string, unknown> { return isRecord(value) && value.format === BELEGE24_DOCUMENT_FORMAT && value.schemaVersion === BELEGE24_SCHEMA_VERSION && isMetadata(value.document, documentType) && isSharedData(value.sharedData) && isRecord(value.documentData); }
function createSharedData(data: BusinessData): SharedData {
  const footer = data.footer;
  return { sender: { brandName: data.sender.companyName, senderLine: data.sender.returnAddress, address: { ...data.sender.address }, companyFooter: { columns: [{ fields: [{ key: 'companyName', value: footer.company.companyName }, { key: 'streetAndNumber', value: `${footer.company.street} ${footer.company.houseNumber}` }, { key: 'postalCodeAndCity', value: `${footer.company.postalCode} ${footer.company.city}` }, { key: 'custom', value: footer.company.extra }] }, { fields: [{ key: 'vatId', value: footer.tax.vatId }, { key: 'taxNumber', value: footer.tax.taxNumber }, { key: 'commercialRegister', value: footer.tax.commercialRegister }, { key: 'custom', value: footer.tax.representation }] }, { fields: [{ key: 'bankName', value: footer.bank.bankName }, { key: 'iban', value: footer.bank.iban }, { key: 'bic', value: footer.bank.bic }, { key: 'custom', value: footer.bank.bankExtra }] }], companyAddress: { street: footer.company.street, houseNumber: footer.company.houseNumber, postalCode: footer.company.postalCode, city: footer.company.city } } }, recipient: { company: data.recipient.companyName, contactPerson: data.recipient.attention, department: data.recipient.name, streetAndNumber: '', countryPostalCodeAndCity: '', address: { ...data.recipient.address }, customerNumber: data.references.customerNumber ?? data.references.customerReference ?? '' } };
}
function documentShell<T extends 'offer' | 'deliveryNote' | 'receipt' | 'selfReceipt' | 'businessLetter', D extends object>(documentType: T, data: BusinessData, documentData: D) {
  return { format: BELEGE24_DOCUMENT_FORMAT, schemaVersion: BELEGE24_SCHEMA_VERSION, document: { documentType, documentId: crypto.randomUUID(), createdAt: new Date().toISOString(), generatorVersion: BELEGE24_GENERATOR_VERSION }, sharedData: createSharedData(data), documentData } satisfies Belege24Document<T, D>;
}

export function mapOfferToDocument(state: OfferEditorState): OfferDocument { return documentShell('offer', state.offerData, { state: { labels: { ...state.labels }, documentData: structuredClone(state.offerData), positions: state.positions.map((position) => ({ ...position })), textBlocks: state.textBlocks.map((block) => ({ ...block })), fieldConfig: structuredClone(state.fieldConfig) } }); }
export function mapDeliveryNoteToDocument(state: DeliveryNoteEditorState): DeliveryNoteDocument { return documentShell('deliveryNote', state.deliveryNoteData, { state: { labels: { ...state.labels }, documentData: structuredClone(state.deliveryNoteData), positions: state.positions.map((position) => ({ ...position })), textBlocks: state.textBlocks.map((block) => ({ ...block })), fieldConfig: structuredClone(state.fieldConfig) } }); }
function normalizeSelfReceiptFieldConfig(fieldConfig: unknown): SelfReceiptEditorState['fieldConfig'] {
  const config = fieldConfig as SelfReceiptEditorState['fieldConfig'];
  const expenseInfo = isRecord(config) && isSelfReceiptExpenseInfoConfig(config.expenseInfo)
    ? config.expenseInfo
    : null;
  return {
    ...structuredClone(config),
    expenseInfo: expenseInfo
      ? {
        hidden: expenseInfo.hidden.filter((field) => selfReceiptExpenseInfoFields.includes(field)),
        order: selfReceiptExpenseInfoFields.filter((field) => expenseInfo.order.includes(field)),
      }
      : { hidden: [], order: [...selfReceiptExpenseInfoFields] },
    signature: isRecord(config) && isConfig(config.signature, selfReceiptSignatureFields)
      ? structuredClone(config.signature)
      : { hidden: [], order: [...selfReceiptSignatureFields] },
  };
}
function normalizeShortSelfReceiptFieldConfig(fieldConfig: unknown): NonNullable<SelfReceiptEditorState['shortSelfReceipt']>['fieldConfig'] {
  const config = fieldConfig as NonNullable<SelfReceiptEditorState['shortSelfReceipt']>['fieldConfig'];
  return {
    signature: isRecord(config) && isConfig(config.signature, shortSelfReceiptSignatureFields)
      ? structuredClone(config.signature)
      : { hidden: [], order: [...shortSelfReceiptSignatureFields] },
    header: isRecord(config) && isConfig(config.header, shortSelfReceiptHeaderFields)
      ? structuredClone(config.header)
      : { hidden: [], order: [...shortSelfReceiptHeaderFields] },
  };
}
function isShortSelfReceipt(value: unknown): boolean { return isRecord(value) && hasStrings(value, ['title', 'receiptNumber', 'recipientAddress', 'purpose', 'reason', 'date']) && (!('dateLabel' in value) || typeof value.dateLabel === 'string') && (!('signatureLabel' in value) || typeof value.signatureLabel === 'string') && (!('signatureValue' in value) || typeof value.signatureValue === 'string') && (!('ownAddress' in value) || hasStrings(value.ownAddress, ['company', 'street', 'cityLine'])) && isRecord(value.amount) && hasStrings(value.amount, ['calculationSource', 'sourceAmount', 'taxRate']) && (value.amount.calculationSource === 'netAmount' || value.amount.calculationSource === 'grossAmount') && isRecord(value.fieldConfig) && isConfig(value.fieldConfig.signature, shortSelfReceiptSignatureFields) && (!('header' in value.fieldConfig) || isConfig(value.fieldConfig.header, shortSelfReceiptHeaderFields)); }
function createSelfReceiptState(state: SelfReceiptEditorState): SelfReceiptEditorState {
  const normalized = {
    labels: Object.fromEntries(selfReceiptLabels.map((key) => [key, state.labels[key]])),
    selfReceiptData: structuredClone(state.selfReceiptData),
    positions: state.positions.map(({ id, description, netAmount, taxRate }) => ({ id, description, netAmount, taxRate })),
    fieldConfig: normalizeSelfReceiptFieldConfig(state.fieldConfig),
  } as SelfReceiptEditorState;

  if (state.selfReceiptVariant) normalized.selfReceiptVariant = state.selfReceiptVariant;
  if (state.shortSelfReceipt) normalized.shortSelfReceipt = {
    ...structuredClone(state.shortSelfReceipt),
    dateLabel: typeof state.shortSelfReceipt.dateLabel === 'string' ? state.shortSelfReceipt.dateLabel : 'Datum',
    signatureLabel: typeof state.shortSelfReceipt.signatureLabel === 'string' ? state.shortSelfReceipt.signatureLabel : 'Stempel / Unterschrift',
    signatureValue: typeof state.shortSelfReceipt.signatureValue === 'string' ? state.shortSelfReceipt.signatureValue : '',
    ownAddress: isRecord(state.shortSelfReceipt.ownAddress) && hasStrings(state.shortSelfReceipt.ownAddress, ['company', 'street', 'cityLine'])
      ? structuredClone(state.shortSelfReceipt.ownAddress)
      : { company: '', street: '', cityLine: '' },
    fieldConfig: normalizeShortSelfReceiptFieldConfig(state.shortSelfReceipt.fieldConfig),
  };

  return normalized;
}
export function mapSelfReceiptToDocument(state: SelfReceiptEditorState): SelfReceiptDocument { const { selfReceiptData } = state; const business: BusinessData = { sender: selfReceiptData.sender, recipient: selfReceiptData.recipient, details: selfReceiptData.details, references: selfReceiptData.references, footer: selfReceiptData.footer }; return documentShell('selfReceipt', business, { state: createSelfReceiptState(state) }); }
function createBusinessLetterState(state: BusinessLetterGeneratorState): BusinessLetterGeneratorState { const { distribution: _distribution, ...content } = state.content as BusinessLetterGeneratorState['content'] & { distribution?: string }; const { distribution: _distributionLabel, ...labels } = state.labels; return { ...structuredClone(state), labels, content, fieldConfig: { ...structuredClone(state.fieldConfig), letterContent: { ...state.fieldConfig.letterContent, hidden: state.fieldConfig.letterContent.hidden.filter((field) => field !== 'distribution'), order: state.fieldConfig.letterContent.order.filter((field) => field !== 'distribution') } } } as BusinessLetterGeneratorState; }
export function mapBusinessLetterToDocument(state: BusinessLetterGeneratorState): BusinessLetterDocument { return documentShell('businessLetter', state.letterData, { state: createBusinessLetterState(state) }); }

function isOfferState(value: unknown): value is OfferDocument['documentData']['state'] { return isRecord(value) && isStringRecord(value.labels, offerLabels) && isBusinessData(value.documentData, ['offerNumber', 'offerDate', 'validUntil'], ['internalNumber', 'externalNumber', 'customerNumber']) && Array.isArray(value.positions) && value.positions.length > 0 && value.positions.every((position) => isRecord(position) && hasStrings(position, ['id', 'description', 'unitPrice', 'quantity', 'unit', 'taxRate']) && typeof position.id === 'string' && uuidPattern.test(position.id)) && isTextBlocks(value.textBlocks, ['intro', 'closing']) && isBusinessFieldConfig(value.fieldConfig, businessConfigFields.details); }
function isDeliveryState(value: unknown): value is DeliveryNoteDocument['documentData']['state'] { return isRecord(value) && isStringRecord(value.labels, deliveryLabels) && isBusinessData(value.documentData, ['deliveryNoteNumber', 'deliveryDate', 'orderDate'], ['internalReference', 'externalReference', 'customerReference']) && Array.isArray(value.positions) && value.positions.length > 0 && value.positions.every((position) => isRecord(position) && hasStrings(position, ['id', 'quantity', 'unit', 'description', 'deliveryDate', 'note']) && typeof position.id === 'string' && uuidPattern.test(position.id)) && isTextBlocks(value.textBlocks, ['intro', 'closing']) && isBusinessFieldConfig(value.fieldConfig, ['deliveryNoteNumber', 'deliveryDate', 'orderDate', 'internalReference', 'externalReference', 'customerReference']); }
function isSelfReceiptState(value: unknown): value is SelfReceiptGeneratorState { return isRecord(value) && isStringRecord(value.labels, selfReceiptLabels) && isRecord(value.selfReceiptData) && isBusinessData(value.selfReceiptData, ['selfReceiptId', 'receiptDate', 'expenseDate'], ['internalReference', 'externalReference', 'costCenter']) && hasStrings(value.selfReceiptData.expenseInfo, ['occasion', 'reason', 'settlementType', 'location']) && Array.isArray(value.positions) && value.positions.length > 0 && value.positions.every((position) => isRecord(position) && hasStrings(position, ['id', 'description', 'netAmount', 'taxRate']) && typeof position.id === 'string' && uuidPattern.test(position.id)) && isRecord(value.fieldConfig) && isBusinessFieldConfig(value.fieldConfig, ['selfReceiptId', 'receiptDate', 'expenseDate', 'internalReference', 'externalReference', 'costCenter']) && (!('expenseInfo' in value.fieldConfig) || isSelfReceiptExpenseInfoConfig(value.fieldConfig.expenseInfo)) && (!('signature' in value.fieldConfig) || isConfig(value.fieldConfig.signature, selfReceiptSignatureFields)) && (!('selfReceiptVariant' in value) || value.selfReceiptVariant === 'standard' || value.selfReceiptVariant === 'short') && (!('shortSelfReceipt' in value) || isShortSelfReceipt(value.shortSelfReceipt)) && (value.selfReceiptVariant !== 'short' || isShortSelfReceipt(value.shortSelfReceipt)); }
function isBusinessLetterState(value: unknown): value is BusinessLetterGeneratorState { return isRecord(value) && isStringRecord(value.labels, businessLetterLabels) && isBusinessData(value.letterData, ['yourReference', 'ourReference', 'contactPerson', 'place', 'letterDate'], []) && hasStrings(value.content, ['subject', 'salutation', 'body', 'closing', 'signerName', 'signerRole', 'attachments']) && isRecord(value.fieldConfig) && isBusinessFieldConfig(value.fieldConfig, ['yourReference', 'ourReference', 'contactPerson', 'place', 'letterDate']) && (isConfig(value.fieldConfig.letterContent, ['signerRole', 'attachments']) || isConfig(value.fieldConfig.letterContent, ['signerRole', 'attachments', 'distribution'])); }
export function restoreOfferState(value: unknown): RestoreResult<OfferEditorState> { if (!isRecord(value) || !isRecord(value.document) || value.document.documentType !== 'offer') return { status: 'wrong-document-type' }; if (!hasBaseDocument(value, 'offer') || !isRecord(value.documentData) || !isOfferState(value.documentData.state)) return { status: 'invalid' }; const state = value.documentData.state; return { status: 'valid', state: { labels: { ...state.labels }, offerData: structuredClone(state.documentData), positions: state.positions.map((position) => ({ ...position })), textBlocks: state.textBlocks.map((block) => ({ ...block })), fieldConfig: structuredClone(state.fieldConfig) } }; }
export function restoreDeliveryNoteState(value: unknown): RestoreResult<DeliveryNoteEditorState> { if (!isRecord(value) || !isRecord(value.document) || value.document.documentType !== 'deliveryNote') return { status: 'wrong-document-type' }; if (!hasBaseDocument(value, 'deliveryNote') || !isRecord(value.documentData) || !isDeliveryState(value.documentData.state)) return { status: 'invalid' }; const state = value.documentData.state; return { status: 'valid', state: { labels: { ...state.labels }, deliveryNoteData: structuredClone(state.documentData), positions: state.positions.map((position) => ({ ...position })), textBlocks: state.textBlocks.map((block) => ({ ...block })), fieldConfig: structuredClone(state.fieldConfig) } }; }
export function restoreSelfReceiptState(value: unknown): RestoreResult<SelfReceiptEditorState> { if (!isRecord(value) || !isRecord(value.document) || value.document.documentType !== 'selfReceipt') return { status: 'wrong-document-type' }; if (!hasBaseDocument(value, 'selfReceipt') || !isRecord(value.documentData) || !isSelfReceiptState(value.documentData.state)) return { status: 'invalid' }; return { status: 'valid', state: createSelfReceiptState(value.documentData.state) }; }
export function restoreBusinessLetterState(value: unknown): RestoreResult<BusinessLetterGeneratorState> { if (!isRecord(value) || !isRecord(value.document) || value.document.documentType !== 'businessLetter') return { status: 'wrong-document-type' }; if (!hasBaseDocument(value, 'businessLetter') || !isRecord(value.documentData) || !isBusinessLetterState(value.documentData.state)) return { status: 'invalid' }; return { status: 'valid', state: createBusinessLetterState(value.documentData.state) }; }

function isReceiptData(value: unknown): boolean { return isRecord(value) && isRecord(value.sender) && hasStrings(value.sender, ['companyName', 'returnAddress']) && isAddress(value.sender.address) && hasStrings(isRecord(value.sender) ? value.sender.contact : undefined, ['email', 'phone', 'website']) && isRecord(value.recipient) && hasStrings(value.recipient, ['companyName', 'attention', 'name']) && isAddress(value.recipient.address) && hasStrings(value.details, ['receiptId', 'receiptDate', 'paymentDate', 'place', 'from', 'purpose', 'bookingNote', 'receiverSignature']) && hasStrings(value.references, ['internalReference', 'externalReference']) && isRecord(value.amount) && hasStrings(value.amount, ['calculationSource', 'sourceAmount', 'taxRate', 'amountInWords', 'settlementMethod']) && (value.amount.calculationSource === 'netAmount' || value.amount.calculationSource === 'grossAmount') && isRecord(value.footer) && hasStrings(value.footer.company, ['companyName', 'street', 'houseNumber', 'postalCode', 'city', 'extra']) && hasStrings(value.footer.tax, ['vatIdLabel', 'vatId', 'taxIdLabel', 'taxId', 'representation']) && hasStrings(value.footer.bank, ['bankName', 'ibanLabel', 'iban', 'bicLabel', 'bic']); }
function isReceiptState(value: unknown): boolean { return isRecord(value) && isStringRecord(value.labels, receiptLabels) && isReceiptData(value.receiptData) && (value.amountCalculationSource === 'netAmount' || value.amountCalculationSource === 'grossAmount') && isTextBlocks(value.textBlocks, ['receiptText', 'purpose']) && isRecord(value.fieldConfig) && isConfig(value.fieldConfig.contact, ['email', 'phone', 'website']) && isConfig(value.fieldConfig.details, ['receiptId', 'receiptDate', 'paymentDate', 'internalReference', 'externalReference']) && isConfig(value.fieldConfig.header, ['company', 'streetLine', 'cityLine']) && isConfig(value.fieldConfig.recipient, ['attention', 'name']) && isConfig(value.fieldConfig.footerMiddle, ['vatId', 'taxId', 'representation']); }
function parseAmount(value: string): number | null { const normalized = value.trim().replace(/\s/g, '').replace(/\./g, '').replace(',', '.'); const result = Number.parseFloat(normalized); return normalized && Number.isFinite(result) ? result : null; }
function formatAmount(value: number): string { return new Intl.NumberFormat('de-DE', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value); }
function restoreReceiptAmount(amount: ReceiptPersistedGeneratorState['receiptData']['amount']) { const source = parseAmount(amount.sourceAmount); const taxRate = amount.taxRate.trim() === '' ? 0 : parseAmount(amount.taxRate); if (source === null || taxRate === null) return { netAmount: amount.calculationSource === 'netAmount' ? amount.sourceAmount : '', taxRate: amount.taxRate, taxAmount: '', grossAmount: amount.calculationSource === 'grossAmount' ? amount.sourceAmount : '', amountInWords: amount.amountInWords, settlementMethod: amount.settlementMethod }; if (amount.calculationSource === 'grossAmount') { const net = source / (1 + taxRate / 100); return { netAmount: formatAmount(net), taxRate: amount.taxRate, taxAmount: formatAmount(source - net), grossAmount: amount.sourceAmount, amountInWords: amount.amountInWords, settlementMethod: amount.settlementMethod }; } const tax = source * (taxRate / 100); return { netAmount: amount.sourceAmount, taxRate: amount.taxRate, taxAmount: formatAmount(tax), grossAmount: formatAmount(source + tax), amountInWords: amount.amountInWords, settlementMethod: amount.settlementMethod }; }
export function mapReceiptToDocument(state: ReceiptGeneratorState): ReceiptDocument { const persisted: ReceiptPersistedGeneratorState = { labels: { ...state.labels }, receiptData: { ...structuredClone(state.receiptData), amount: { calculationSource: state.amountCalculationSource, sourceAmount: state.amountCalculationSource === 'grossAmount' ? state.receiptData.amount.grossAmount : state.receiptData.amount.netAmount, taxRate: state.receiptData.amount.taxRate, amountInWords: state.receiptData.amount.amountInWords, settlementMethod: state.receiptData.amount.settlementMethod } }, amountCalculationSource: state.amountCalculationSource, textBlocks: state.textBlocks.map((block) => ({ ...block })), fieldConfig: structuredClone(state.fieldConfig) }; const business: BusinessData = { sender: { ...persisted.receiptData.sender, contact: { ...persisted.receiptData.sender.contact, fax: '' } }, recipient: persisted.receiptData.recipient, details: persisted.receiptData.details, references: persisted.receiptData.references, footer: { company: persisted.receiptData.footer.company, tax: { vatIdLabel: persisted.receiptData.footer.tax.vatIdLabel, vatId: persisted.receiptData.footer.tax.vatId, taxNumberLabel: persisted.receiptData.footer.tax.taxIdLabel, taxNumber: persisted.receiptData.footer.tax.taxId, commercialRegister: '', representation: persisted.receiptData.footer.tax.representation }, bank: { ...persisted.receiptData.footer.bank, bankExtra: '' } } }; return documentShell('receipt', business, { state: persisted }) as ReceiptDocument; }
export function restoreReceiptState(value: unknown): RestoreResult<ReceiptGeneratorState> { if (!isRecord(value) || !isRecord(value.document) || value.document.documentType !== 'receipt') return { status: 'wrong-document-type' }; if (!hasBaseDocument(value, 'receipt') || !isRecord(value.documentData) || !isReceiptState(value.documentData.state)) return { status: 'invalid' }; const state = value.documentData.state as ReceiptPersistedGeneratorState; return { status: 'valid', state: { labels: { ...state.labels }, receiptData: { ...structuredClone(state.receiptData), amount: restoreReceiptAmount(state.receiptData.amount) }, amountCalculationSource: state.amountCalculationSource, textBlocks: state.textBlocks.map((block) => ({ ...block })), fieldConfig: structuredClone(state.fieldConfig) } }; }

export function validateOfferDocument(value: unknown) { return restoreOfferState(value).status === 'valid' ? { valid: true, errors: [] } : { valid: false, errors: ['offer document is invalid'] }; }
export function validateDeliveryNoteDocument(value: unknown) { return restoreDeliveryNoteState(value).status === 'valid' ? { valid: true, errors: [] } : { valid: false, errors: ['delivery note document is invalid'] }; }
export function validateReceiptDocument(value: unknown) { return restoreReceiptState(value).status === 'valid' ? { valid: true, errors: [] } : { valid: false, errors: ['receipt document is invalid'] }; }
export function validateSelfReceiptDocument(value: unknown) { return restoreSelfReceiptState(value).status === 'valid' ? { valid: true, errors: [] } : { valid: false, errors: ['self receipt document is invalid'] }; }
export function validateBusinessLetterDocument(value: unknown) { return restoreBusinessLetterState(value).status === 'valid' ? { valid: true, errors: [] } : { valid: false, errors: ['business letter document is invalid'] }; }

function statesEqual<T>(first: T, second: T): boolean { return JSON.stringify(first) === JSON.stringify(second); }
export const areOfferStatesEqual = statesEqual<OfferEditorState>;
export const areDeliveryNoteStatesEqual = statesEqual<DeliveryNoteEditorState>;
export const areReceiptStatesEqual = statesEqual<ReceiptGeneratorState>;
export const areSelfReceiptStatesEqual = statesEqual<SelfReceiptEditorState>;
export const areBusinessLetterStatesEqual = statesEqual<BusinessLetterGeneratorState>;
export function confirmOfferOverwrite(current: OfferEditorState, initial: OfferEditorState, confirm: () => boolean) { return areOfferStatesEqual(current, initial) || confirm(); }
export function confirmDeliveryNoteOverwrite(current: DeliveryNoteEditorState, initial: DeliveryNoteEditorState, confirm: () => boolean) { return areDeliveryNoteStatesEqual(current, initial) || confirm(); }
export function confirmReceiptOverwrite(current: ReceiptGeneratorState, initial: ReceiptGeneratorState, confirm: () => boolean) { return areReceiptStatesEqual(current, initial) || confirm(); }
export function confirmSelfReceiptOverwrite(current: SelfReceiptEditorState, initial: SelfReceiptEditorState, confirm: () => boolean) { return areSelfReceiptStatesEqual(current, initial) || confirm(); }
export function confirmBusinessLetterOverwrite(current: BusinessLetterGeneratorState, initial: BusinessLetterGeneratorState, confirm: () => boolean) { return areBusinessLetterStatesEqual(current, initial) || confirm(); }
async function importAdditionalPdf<T>(bytes: ArrayBuffer | Uint8Array, documentType: string, restore: (value: unknown) => RestoreResult<T>): Promise<AdditionalPdfImportResult<T>> { const result = await readBelege24DocumentFromPdf(bytes); if (result.status === 'not-found') return { status: 'not-found', message: 'Diese PDF enthält keine Belege24-Daten.' }; if (result.status === 'unsupported') return { status: 'unsupported', message: 'Die Format- oder Schema-Version dieser Belege24-PDF wird nicht unterstützt.' }; if (result.status === 'unreadable-pdf') return { status: 'unreadable-pdf', message: 'Die PDF konnte nicht gelesen werden.' }; if (result.status === 'invalid-json' || result.status === 'invalid-document') return { status: 'invalid-data', message: 'Die eingebetteten Belege24-Daten sind ungültig oder beschädigt.' }; if (result.document.document.documentType !== documentType) return { status: 'wrong-document-type', message: `Die PDF enthält keinen Belege24-Datensatz für ${documentType === 'offer' ? 'ein Angebot' : documentType === 'deliveryNote' ? 'einen Lieferschein' : documentType === 'selfReceipt' ? 'einen Eigenbeleg' : documentType === 'businessLetter' ? 'einen Geschäftsbrief' : 'eine Quittung'}.` }; const restored = restore(result.document); return restored.status === 'valid' ? { status: 'valid', state: restored.state, message: 'PDF erfolgreich geladen.' } : { status: restored.status === 'wrong-document-type' ? 'wrong-document-type' : 'invalid-data', message: 'Die eingebetteten Belege24-Daten sind ungültig oder beschädigt.' }; }
export const importOfferPdf = (bytes: ArrayBuffer | Uint8Array) => importAdditionalPdf(bytes, 'offer', restoreOfferState);
export const importDeliveryNotePdf = (bytes: ArrayBuffer | Uint8Array) => importAdditionalPdf(bytes, 'deliveryNote', restoreDeliveryNoteState);
export const importReceiptPdf = (bytes: ArrayBuffer | Uint8Array) => importAdditionalPdf(bytes, 'receipt', restoreReceiptState);
export const importSelfReceiptPdf = (bytes: ArrayBuffer | Uint8Array) => importAdditionalPdf(bytes, 'selfReceipt', restoreSelfReceiptState);
export const importBusinessLetterPdf = (bytes: ArrayBuffer | Uint8Array) => importAdditionalPdf(bytes, 'businessLetter', restoreBusinessLetterState);
